<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CocinaManager.Domain\CocinaManager.Domain.csproj" />
  </ItemGroup>

</Project>
